# This file is for various variables used throughout the workflow.
# See a description of each setting in the README.md file.
input_dir: "/raw_data/MD/MD_P081/PacBio/r84150_20250820_115740/demux/barcodes"
output_dir: "output"
tmp_dir: "tmp"
log_dir: "logs"
db_sintax: "/databases/midas/MiDAS5.3_20240320/FLASVs_w_sintax.fa"
# to skip filtering altogether set to "--min_length 1"
filtlong_args: "--min_length 200 --min_mean_q 90"
max_threads: 32
sample_sep: "_"
# options passed on to cutadapt directly. Input, output, and threads are added automatically
cutadapt_args: "-g AGRGTTYGATYMTGGCTCAG...GTTTGGCACCTCGATGTCG --revcomp --discard-untrimmed"
derep_minsize: 2
unoise_minsize: 8
rarefy_abund_table: False
rarefy_sample_size: 2000
